### PR TITLE
Added credits to README & added the Czech translation

### PR DESCRIPTION
**Pull request by nwvh**
Added the translation for Czech language

### CODE REVIEW

**Comment by DevilXD** [comment]
Hello o/

Looks good! Only note I want to make here, is that - the filename of the translation file, will be the name that's displayed in the application as a choice. You've used `chech.json`, which will display the translation as `chech`. Please rename the file to `Chech.json`, so that the language name starts with a capital letter :slightly_smiling_face:

**Comment by DevilXD** [comment]
Does "Vynecháno" work as a Czech translation for "Excluded"?

**Comment by nwvh** [comment]
> Does "Vynecháno" work for you as a Czech translation for "Excluded"?

yes

**Comment by DevilXD** [comment]
Cool, thank you for your contribution :slightly_smiling_face:

**Comment by nwvh** [comment]
happy to help

**Pull request merged**
