### PR TITLE
refactor twitch.py state change loop

### PR DESCRIPTION
**Pull request by EB-Plum**
trying to separate _run method which is too long to read

mostly just cuts and pastes of original codes

### CODE REVIEW

**Comment by DevilXD** [comment]
Hello. What exactly is the purpose of this change?

**Comment by EB-Plum** [comment]
Hello, this pr is just for minor readability.
No functionality change intended.

found it was too long for single function, while i was figuring out how to shorten the refresh loop.

**Comment by DevilXD** [comment]
I see no point then. Also, the refresh loop shouldn't be shortened, as that puts more strain on Twitch servers, which ultimately leads to Twitch doing more and more to block this thing. Please try not to contribute to this project's eventual demise.

**Comment by EB-Plum** [comment]
oh sorry, didn't think that way...
guess i should find other way to mining short campaigns.

**Pull request closed without merging**
