### PR TITLE
Linux improvements & development builds

### LINKED ISSUE #113: Linux binary
In #35 linux support got added and released with v15 and it's working like a charm.
As of the last comment by Devil I tried my best to make an executable with some instructions but failed.

# What I found out:

- You can also use pyinstaller for building binaries in Linux.
- python3.10 is not working with pyinstaller at all (it's an unsupported bug party) so I decided to use 3.11.

I had some big trouble settings up tkinter, and it looks like I still have (maybe).
**Important**
You have to install tkinter besides of pip. (sudo apt-get install tcl-dev && tk-dev), check for weird paths mine wasn't stored in `/usr/lib/tcltk/` but instead in `/usr/share/tcltk`

Many fails later I finally managed to run pyinstaller and build an executable (yey) but now I'm stuck again and have no clue what's wrong and wth I'm doing wrong...

After using this [build.spec](https://github.com/DevilXD/TwitchDropsMiner/files/10348822/build.txt) file I was able to build an executable with this output:
[pyinstaller.txt](https://github.com/DevilXD/TwitchDropsMiner/files/10348836/pyinstaller.txt)

After investigating, I found those WARNINGS:
```
1408 WARNING: Cannot find libwebp-112793e9.so.7.1.5 (needed by /path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/PIL/../Pillow.libs/libwebpmux-87a21b3d.so.3.0.10)
1435 WARNING: Cannot find libwebp-112793e9.so.7.1.5 (needed by /path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/PIL/../Pillow.libs/libwebpdemux-855d485d.so.2.0.11)
1464 WARNING: Cannot find libXau-154567c4.so.6.0.0 (needed by /path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/PIL/../Pillow.libs/libxcb-3e83370d.so.1.1.0)
1479 WARNING: Cannot find liblzma-160b9c62.so.5.4.0 (needed by /path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/PIL/../Pillow.libs/libtiff-b9364ff1.so.6.0.0)
1479 WARNING: Cannot find libjpeg-16b2c4cf.so.62.3.0 (needed by /path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/PIL/../Pillow.libs/libtiff-b9364ff1.so.6.0.0)
```

So I searched for those files and all of them are present...
```/path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/Pillow.libs/libwebp-112793e9.so.7.1.5
/path/to/TwitchDropsMiner/dist/main/libwebp-112793e9.so.7.1.5
/home/kali/.cache/pyinstaller/bincache00_py311_64bit/libwebp-112793e9.so.7.1.5

/path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/Pillow.libs/libXau-154567c4.so.6.0.0
/path/to/TwitchDropsMiner/dist/main/libXau-154567c4.so.6.0.0
/home/kali/.cache/pyinstaller/bincache00_py311_64bit/libXau-154567c4.so.6.0.0

/path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/Pillow.libs/liblzma-160b9c62.so.5.4.0
/path/to/TwitchDropsMiner/dist/main/liblzma-160b9c62.so.5.4.0
/home/kali/.cache/pyinstaller/bincache00_py311_64bit/liblzma-160b9c62.so.5.4.0

/path/to/TwitchDropsMiner/env/lib/python3.11/site-packages/Pillow.libs/libjpeg-16b2c4cf.so.62.3.0
/path/to/TwitchDropsMiner/dist/main/libjpeg-16b2c4cf.so.62.3.0
/home/kali/.cache/pyinstaller/bincache00_py311_64bit/libjpeg-16b2c4cf.so.62.3.0
```

Now to the actual error when starting the compiled binary:
```
Traceback (most recent call last):
  File "PIL/ImageTk.py", line 65, in _pyimagingtkcall
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 99, in <module>
  File "PIL/ImageTk.py", line 130, in __init__
  File "PIL/ImageTk.py", line 190, in paste
  File "PIL/ImageTk.py", line 69, in _pyimagingtkcall
ModuleNotFoundError: No module named 'PIL._tkinter_finder'
[1337244] Failed to execute script 'main' due to unhandled exception!
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/_MEIuAc0OX/pickaxe.ico'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

I'm unsure if everything is clear I made a TON of "fixes" without even knowing anymore, so some information might be missing. If this helps, great if not well...

I hope someone catches up on this. Cheers

### PR DESCRIPTION
**Pull request by guihkx**
This adds many Linux improvements and fixes (more details in each commit's description).

This also adds support for development builds for Linux through GitHub Actions.

Closes #113

### CODE REVIEW

**Comment by DevilXD** [comment]
Very well. I've added some small stylistic and wording modifications from my side, which you can find on my `linux` branch. Please make them a part of this PR as well. The Windows build notes aren't really fitting too much in this PR, but I wanted to avoid any potential merge conflicts later on, and the `linux` branch is going to disappear anyway, so outside of this PR, there will be no trace of which branch the commit came from.

**Comment by guihkx** [comment]
Thanks! Is it okay if I squash your commits into mine and add you as a co-author instead of pushing them directly into the branch I'm working on? I personally think that's more organized.

**Comment by DevilXD** [comment]
Honestly, I don't really care, as long as it keeps the expected structure - a single commit message explains a single addition. You'll probably have to edit some commit message(s) to get it right, but sure, you can squash them.

I pushed those 3 commits right before going to sleep, and didn't catch some missing backticks here and there, so there's a 4th commit now. You can squash that commit too as well.

**Comment by guihkx** [comment]
Alright, done. Let me know if the commits look good enough.

**Review by DevilXD — APPROVED** [review]
Very well. Thank you so much for your contribution :blush:

**Pull request merged**
