### PR TITLE
Added Traditional Chinese Translation

### PR DESCRIPTION
**Pull request by Ricky103403**
I added a Traditional Chinese(繁體中文) Translation.
Please check it, thanks.

### CODE REVIEW

**Comment by DevilXD** [comment]
Hello o/

Pardon my blissfulness, but there already is a Chinese translation added to the application. How exactly is this one different?

Also paging @Suz1e for a review and opinion on this and the already existing translation, as I'm not entirely sure what's the difference and purpose of this one even.

**Comment by Ricky103403** [comment]
Traditional Chinese(繁體中文) and Simplified Chinese(簡體中文) is different.

Generally speaking, the either traditional Chinese or simplified Chinese mostly refers to the characters themselves, that is, how they are written.

Or you can understand as same character with 2 different forms, for example the character of "write" in Chinese, the traditional form is "寫" and the simplified form is "写".

**Comment by Fidelxyz** [comment]
Yes they are different - from a native Chinese speaker

They are used by those who live in different regions of China - the mainland of China and other regions including Hong Kong, Macau, and Taiwan

Also both these language options frequently present in many apps at the same time

**Comment by DevilXD** [comment]
Alright, well, since I don't see any issues with it, maybe beyond having to support two Chinese translations at the same time, sure. I'm leaving any updates, changes and adjustments up to possible future PRs from others only.

**Pull request merged**
